from typing import List

config_default: List[str] = [
    r"# --------- General Settings --------- #",
    r"",
    r'# Options: "Continuous", "Random"',
    r'mode: "Continuous"',
    r"",
    r"# Options: (Any number. Larger sample sizes require longer to process).",
    r'# Note: A sample size greater than the specified range will cap out at the range value, acting as "Continuous".',
    r"sample-size: 5000",
    r"",
    r'# Options: "Linear", "Logarithmic".',
    r'scaling: "Linear" #',
    r"",
    r"# Options: (Any decimal number n where 0 < n < 360)",
    r"angle-if-odd: 8.0 #",
    r"angle-if-even: 16.0 #",
    r"",
    r"# --------- Style Settings --------- #",
    r"",
    r'# Options: "Flat", "Gradient"',
    r'color-scheme: "Gradient"',
    r"",
    r"# Options: (Any valid RGBA hex code).",
    r'background-color: "#000000FF"',
    r"",
    r"# Options: (Any valid RGBA hex code).",
    r'# Note: If "colorScheme" is "flat", the first color in this sequence will be used throughout.',
    r'gradient: "#000000FF, #FFFFFFFF"',
    r"",
    r'# Options: "Length-based", "Frequency-based".',
    r'# Note: These options only kick in if "color-scheme" is set to "Gradient".',
    r'color-based-on: "Frequency-based"',
    r"",
    r"# Options: (Any value =/< 255) [in px]",
    r'# Line length acts as the maximum length a segment can take. This is the value taken by "Linear" scaling, influenced by "Logarithmic" scaling.',
    r"line-width: 3 #",
    r"line-length: 7 #",
    r"",
    r"# Options: (Any number, [Width]x[Height] in px. Extremely large image sizes will impact performance significantly).",
    r'image-size: "2000x2000" #',
]
